Test actions

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,6 +1,9 @@
-name: Build
+name: Java CI Split
 
 on: [push]
+
+env:
+  INTEGRATION_TESTS_SECRETS_ENV: ${{ secrets.INTEGRATION_TESTS_SECRETS_ENV }}
 
 jobs:
   build:
@@ -19,3 +22,83 @@ jobs:
       - name: Build with Gradle
         run: |
           ./gradlew assemble
+
+  test:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          submodules: 'true'
+      - name: Set up JDK 17
+        uses: actions/setup-java@v1
+        with:
+          java-version: 17
+          cache: 'gradle'
+      - name: Prepare env
+        run: |
+          echo ${INTEGRATION_TESTS_SECRETS_ENV} | base64 -d > tests/config/secrets.env
+      - name: Build with Gradle
+        run: ./gradlew --continue test
+      - uses: actions/upload-artifact@v2
+        with:
+        name: reports
+        path: '**/TEST-*.xml'
+
+  slowTest:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          submodules: 'true'
+      - name: Set up JDK 17
+        uses: actions/setup-java@v1
+        with:
+          java-version: 17
+          cache: 'gradle'
+      - name: Prepare env
+        run: |
+          echo ${INTEGRATION_TESTS_SECRETS_ENV} | base64 -d > tests/config/secrets.env
+      - name: Build with Gradle
+        run: ./gradlew --continue  slowTest
+      - uses: actions/upload-artifact@v2
+        with:
+        name: reports
+        path: '**/TEST-*.xml'
+
+  integrationTest:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          submodules: 'true'
+      - name: Set up JDK 17
+        uses: actions/setup-java@v1
+        with:
+          java-version: 17
+          cache: 'gradle'
+      - name: Prepare env
+        run: |
+          echo ${INTEGRATION_TESTS_SECRETS_ENV} | base64 -d > tests/config/secrets.env
+      - name: Build with Gradle
+        run: ./gradlew --continue integrationTest
+      - uses: actions/upload-artifact@v2
+        with:
+        name: reports
+        path: '**/TEST-*.xml'
+
+  report:
+    needs: [test, slowTest, integrationTest]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download artifacts
+        uses: actions/download-artifact@v2
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths:  '**/TEST-*.xml'
+          #- "*/*/*/*/TEST-*.xml"
+          #- "*/*/*/*/*/TEST-*.xml"
